name: CI/CD for EKS Deployment

on:
  push:
    branches:
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
      
      - name: Compile TypeScript
        run: npm run build
      
      - name: Extract AWS Region
        id: extract-region
        run: |
          region=$(jq -r '.region' bin/config.json)
          echo "REGION=$region" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      
      - name: Bootstrap AWS Account
        run: npx cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess --force aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ env.REGION }}

      - name: Deploy CDK Stack
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ env.REGION }}
        run: npx cdk deploy --all --require-approval never --app "node cdk.out/bin/my-fargate-app-eks-multiple-grpc.js"
