name: CI/CD for EKS Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      operation:
        description: 'Enter operation (deploy or destroy)'
        required: true
        default: deploy

jobs:
  run-cdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Extract AWS Region
        id: extract-region
        run: |
          region=$(jq -r '.region' bin/config.json)
          echo "REGION=$region" >> $GITHUB_ENV
          echo "AWS_IAM_USER=${{ secrets.AWS_IAM_USER }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Bootstrap AWS Account
        if: ${{ github.event.inputs.operation == 'deploy' }}
        run: npx cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess --force aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ env.REGION }}

      - name: Run CDK Operation
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ env.REGION }}
        run: |
          if [ "${{ github.event.inputs.operation }}" == "deploy" ]; then
            npx cdk deploy --all --require-approval never --app "node cdk.out/bin/my-fargate-app-eks-multiple-grpc.js"
          elif [ "${{ github.event.inputs.operation }}" == "destroy" ]; then
            npx cdk destroy --all --force --app "node cdk.out/bin/my-fargate-app-eks-multiple-grpc.js"
          else
            echo "Invalid operation: ${{ github.event.inputs.operation }}"
            exit 1
          fi
